### ISSUE TITLE
Cannot build windows 10 x64!

### ISSUE THREAD

**Issue by mlfarrell** [Microsoft/openssl#41] opened 2017-01-03 20:00 UTC
3>------ Build started: Project: NT-Universal-10.0-Static-Unicode-testapp, Configuration: Release x64 ------
2>LINK : fatal error LNK1181: cannot open input file 'WindowsApp.lib'
2>NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.EXE"' : return code '0x49d'
2>  Stop.
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets(41,5): error MSB3073: The command "build.bat Release x64" exited with code 2.

Please provide fix.  My current project doesn't yet need x64, but this is concerning none the less since I will in the future.

**Comment by khouzam** [comment] 2017-01-30 21:13
Hi @mlfarrell, 

Sorry for not responding earlier,


I think that the issue is actually the same as issue #42. I'm pushing out a fix for this. Can you please try it again?

Sorry for the inconvenience.

**Comment by khouzam** [comment] 2017-05-06 06:34
This should be working now. Please reopen if it's not the case.

**Closed as completed by khouzam** 2017-05-06 06:34 UTC
